GET http://localhost:8001/ 

###

GET http://localhost:8002/name HTTP/1.1

###

POST http://localhost:8000/twokey HTTP/1.1
Content-Type: "text/plain"

"{
    "key": "twokey",
    "val": "this second val"
}"



###
POST http://localhost:8000/name HTTP/1.1
Content-Type: "text/plain"

"Jaem Dessources"

###
POST http://localhost:8000/anotherkey HTTP/1.1
Content-Type: "text/plain"

"{
    "key": "mykey",
    "val": "myval val"
}"
###
POST http://localhost:8000/badkey HTTP/1.1
Content-Type: "text/plain"

"{
    "key": "mykey",
    "val": "myval val"
}""
###
DELETE http://localhost:8000/badkey HTTP/1.1
Content-Type: "application/json"

